app:
  version: "1.0.0"
  log:
    level: "debug"
    historyType: "file"
  server:
    profile: "dev"
    port: "3000"

infra:
  db:
    user: "root"
    password: "password"
    sourceAddrs: ["localhost:3306"]
    replicaAddrs: ["localhost:3307"]
    dbName: "flow"
    filePath: "file:flow.db?cache=shared&mode=rwc"
  redis:
    masterName: "mymaster"
    sentinelAddrs: ["localhost:26379"]
  kafka:
    brokers: ["localhost:9092"]
  sentry:
    dsn: "your-sentry-dsn"

auth:
  google:
    client_id: "71426784723-sssihlsco00trm1l8pv8mprsipoojauf.apps.googleusercontent.com"
    client_secret: "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"
    redirect_url: "http://localhost:3000/api/v1/auth/google/callback"
    scopes:
      - "https://www.googleapis.com/auth/userinfo.email"
      - "https://www.googleapis.com/auth/userinfo.profile"
  kakao:
    client_id: "your-kakao-client-id"
    client_secret: "your-kakao-client-secret"
    redirect_url: "http://localhost:3000/api/v1/auth/kakao/callback"
    scopes:
      - "account_email"
      - "profile_nickname"
  github:
    client_id: "Ov23liioku54VGtjk65j"
    client_secret: "bf7bf87b9a406c7fb2df2c39e332dd447f256e1e"
    redirect_url: "http://localhost:3000/api/v1/auth/github/callback"
    scopes:
      - "user:email"
      - "user:profile"
