// Code generated by counterfeiter. DO NOT EDIT.
package middlewarefakes

import (
	"sync"

	fiber "github.com/gofiber/fiber/v2"
	"github.com/kyh0703/flow/internal/core/middleware"
)

type FakeProjectMiddleware struct {
	IsOwnProjectsStub        func() fiber.Handler
	isOwnProjectsMutex       sync.RWMutex
	isOwnProjectsArgsForCall []struct {
	}
	isOwnProjectsReturns struct {
		result1 fiber.Handler
	}
	isOwnProjectsReturnsOnCall map[int]struct {
		result1 fiber.Handler
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeProjectMiddleware) IsOwnProjects() fiber.Handler {
	fake.isOwnProjectsMutex.Lock()
	ret, specificReturn := fake.isOwnProjectsReturnsOnCall[len(fake.isOwnProjectsArgsForCall)]
	fake.isOwnProjectsArgsForCall = append(fake.isOwnProjectsArgsForCall, struct {
	}{})
	stub := fake.IsOwnProjectsStub
	fakeReturns := fake.isOwnProjectsReturns
	fake.recordInvocation("IsOwnProjects", []interface{}{})
	fake.isOwnProjectsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeProjectMiddleware) IsOwnProjectsCallCount() int {
	fake.isOwnProjectsMutex.RLock()
	defer fake.isOwnProjectsMutex.RUnlock()
	return len(fake.isOwnProjectsArgsForCall)
}

func (fake *FakeProjectMiddleware) IsOwnProjectsCalls(stub func() fiber.Handler) {
	fake.isOwnProjectsMutex.Lock()
	defer fake.isOwnProjectsMutex.Unlock()
	fake.IsOwnProjectsStub = stub
}

func (fake *FakeProjectMiddleware) IsOwnProjectsReturns(result1 fiber.Handler) {
	fake.isOwnProjectsMutex.Lock()
	defer fake.isOwnProjectsMutex.Unlock()
	fake.IsOwnProjectsStub = nil
	fake.isOwnProjectsReturns = struct {
		result1 fiber.Handler
	}{result1}
}

func (fake *FakeProjectMiddleware) IsOwnProjectsReturnsOnCall(i int, result1 fiber.Handler) {
	fake.isOwnProjectsMutex.Lock()
	defer fake.isOwnProjectsMutex.Unlock()
	fake.IsOwnProjectsStub = nil
	if fake.isOwnProjectsReturnsOnCall == nil {
		fake.isOwnProjectsReturnsOnCall = make(map[int]struct {
			result1 fiber.Handler
		})
	}
	fake.isOwnProjectsReturnsOnCall[i] = struct {
		result1 fiber.Handler
	}{result1}
}

func (fake *FakeProjectMiddleware) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.isOwnProjectsMutex.RLock()
	defer fake.isOwnProjectsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeProjectMiddleware) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ middleware.ProjectMiddleware = new(FakeProjectMiddleware)
