CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY,
  email TEXT NOT NULL,
  password TEXT NOT NULL,
  name TEXT NOT NULL,
  bio TEXT,
  update_at TEXT DEFAULT CURRENT_TIMESTAMP,
  create_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tokens (
  id INTEGER PRIMARY KEY,
  user_id INTEGER NOT NULL,
  refresh_token TEXT NOT NULL,
  expires_in INTEGER NOT NULL,
  create_at TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS projects (
  id INTEGER PRIMARY KEY,
  user_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  update_at TEXT DEFAULT CURRENT_TIMESTAMP,
  create_at TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS flows (
  id INTEGER PRIMARY KEY,
  project_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  update_at TEXT DEFAULT CURRENT_TIMESTAMP,
  create_at TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS nodes (
  id INTEGER PRIMARY KEY,
  uuid TEXT NOT NULL,
  flow_id INTEGER NOT NULL,
  type TEXT NOT NULL,
  position TEXT NOT NULL DEFAULT "",
  styles TEXT NOT NULL DEFAULT "",
  width INTEGER NOT NULL,
  height INTEGER NOT NULL,
  hidden INTEGER NOT NULL DEFAULT 0,
  description TEXT NOT NULL DEFAULT '',
  update_at TEXT DEFAULT CURRENT_TIMESTAMP,
  create_at TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (flow_id) REFERENCES flows(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS edges (
  id INTEGER PRIMARY KEY,
  uuid TEXT NOT NULL,
  flow_id INTEGER NOT NULL,
  source TEXT NOT NULL,
  target TEXT NOT NULL,
  type TEXT NOT NULL,
  label TEXT NOT NULL DEFAULT '',
  hidden INTEGER NOT NULL DEFAULT 0,
  marker_end TEXT NOT NULL DEFAULT '',
  update_at TEXT DEFAULT CURRENT_TIMESTAMP,
  create_at TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (flow_id) REFERENCES flows(id) ON DELETE CASCADE
);
