// Code generated by counterfeiter. DO NOT EDIT.
package repositoryfakes

import (
	"context"
	"sync"

	"github.com/kyh0703/flow/internal/core/domain/model"
	"github.com/kyh0703/flow/internal/core/domain/repository"
)

type FakeFlowsRepository struct {
	CreateOneStub        func(context.Context, model.CreateFlowParams) (model.Flow, error)
	createOneMutex       sync.RWMutex
	createOneArgsForCall []struct {
		arg1 context.Context
		arg2 model.CreateFlowParams
	}
	createOneReturns struct {
		result1 model.Flow
		result2 error
	}
	createOneReturnsOnCall map[int]struct {
		result1 model.Flow
		result2 error
	}
	DeleteOneStub        func(context.Context, int64) error
	deleteOneMutex       sync.RWMutex
	deleteOneArgsForCall []struct {
		arg1 context.Context
		arg2 int64
	}
	deleteOneReturns struct {
		result1 error
	}
	deleteOneReturnsOnCall map[int]struct {
		result1 error
	}
	FindByIDStub        func(context.Context, int64) (model.Flow, error)
	findByIDMutex       sync.RWMutex
	findByIDArgsForCall []struct {
		arg1 context.Context
		arg2 int64
	}
	findByIDReturns struct {
		result1 model.Flow
		result2 error
	}
	findByIDReturnsOnCall map[int]struct {
		result1 model.Flow
		result2 error
	}
	PaginationStub        func(context.Context, int64, int, int) ([]model.Flow, int64, error)
	paginationMutex       sync.RWMutex
	paginationArgsForCall []struct {
		arg1 context.Context
		arg2 int64
		arg3 int
		arg4 int
	}
	paginationReturns struct {
		result1 []model.Flow
		result2 int64
		result3 error
	}
	paginationReturnsOnCall map[int]struct {
		result1 []model.Flow
		result2 int64
		result3 error
	}
	UpdateOneStub        func(context.Context, model.PatchFlowParams) error
	updateOneMutex       sync.RWMutex
	updateOneArgsForCall []struct {
		arg1 context.Context
		arg2 model.PatchFlowParams
	}
	updateOneReturns struct {
		result1 error
	}
	updateOneReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeFlowsRepository) CreateOne(arg1 context.Context, arg2 model.CreateFlowParams) (model.Flow, error) {
	fake.createOneMutex.Lock()
	ret, specificReturn := fake.createOneReturnsOnCall[len(fake.createOneArgsForCall)]
	fake.createOneArgsForCall = append(fake.createOneArgsForCall, struct {
		arg1 context.Context
		arg2 model.CreateFlowParams
	}{arg1, arg2})
	stub := fake.CreateOneStub
	fakeReturns := fake.createOneReturns
	fake.recordInvocation("CreateOne", []interface{}{arg1, arg2})
	fake.createOneMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeFlowsRepository) CreateOneCallCount() int {
	fake.createOneMutex.RLock()
	defer fake.createOneMutex.RUnlock()
	return len(fake.createOneArgsForCall)
}

func (fake *FakeFlowsRepository) CreateOneCalls(stub func(context.Context, model.CreateFlowParams) (model.Flow, error)) {
	fake.createOneMutex.Lock()
	defer fake.createOneMutex.Unlock()
	fake.CreateOneStub = stub
}

func (fake *FakeFlowsRepository) CreateOneArgsForCall(i int) (context.Context, model.CreateFlowParams) {
	fake.createOneMutex.RLock()
	defer fake.createOneMutex.RUnlock()
	argsForCall := fake.createOneArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeFlowsRepository) CreateOneReturns(result1 model.Flow, result2 error) {
	fake.createOneMutex.Lock()
	defer fake.createOneMutex.Unlock()
	fake.CreateOneStub = nil
	fake.createOneReturns = struct {
		result1 model.Flow
		result2 error
	}{result1, result2}
}

func (fake *FakeFlowsRepository) CreateOneReturnsOnCall(i int, result1 model.Flow, result2 error) {
	fake.createOneMutex.Lock()
	defer fake.createOneMutex.Unlock()
	fake.CreateOneStub = nil
	if fake.createOneReturnsOnCall == nil {
		fake.createOneReturnsOnCall = make(map[int]struct {
			result1 model.Flow
			result2 error
		})
	}
	fake.createOneReturnsOnCall[i] = struct {
		result1 model.Flow
		result2 error
	}{result1, result2}
}

func (fake *FakeFlowsRepository) DeleteOne(arg1 context.Context, arg2 int64) error {
	fake.deleteOneMutex.Lock()
	ret, specificReturn := fake.deleteOneReturnsOnCall[len(fake.deleteOneArgsForCall)]
	fake.deleteOneArgsForCall = append(fake.deleteOneArgsForCall, struct {
		arg1 context.Context
		arg2 int64
	}{arg1, arg2})
	stub := fake.DeleteOneStub
	fakeReturns := fake.deleteOneReturns
	fake.recordInvocation("DeleteOne", []interface{}{arg1, arg2})
	fake.deleteOneMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeFlowsRepository) DeleteOneCallCount() int {
	fake.deleteOneMutex.RLock()
	defer fake.deleteOneMutex.RUnlock()
	return len(fake.deleteOneArgsForCall)
}

func (fake *FakeFlowsRepository) DeleteOneCalls(stub func(context.Context, int64) error) {
	fake.deleteOneMutex.Lock()
	defer fake.deleteOneMutex.Unlock()
	fake.DeleteOneStub = stub
}

func (fake *FakeFlowsRepository) DeleteOneArgsForCall(i int) (context.Context, int64) {
	fake.deleteOneMutex.RLock()
	defer fake.deleteOneMutex.RUnlock()
	argsForCall := fake.deleteOneArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeFlowsRepository) DeleteOneReturns(result1 error) {
	fake.deleteOneMutex.Lock()
	defer fake.deleteOneMutex.Unlock()
	fake.DeleteOneStub = nil
	fake.deleteOneReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeFlowsRepository) DeleteOneReturnsOnCall(i int, result1 error) {
	fake.deleteOneMutex.Lock()
	defer fake.deleteOneMutex.Unlock()
	fake.DeleteOneStub = nil
	if fake.deleteOneReturnsOnCall == nil {
		fake.deleteOneReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteOneReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeFlowsRepository) FindByID(arg1 context.Context, arg2 int64) (model.Flow, error) {
	fake.findByIDMutex.Lock()
	ret, specificReturn := fake.findByIDReturnsOnCall[len(fake.findByIDArgsForCall)]
	fake.findByIDArgsForCall = append(fake.findByIDArgsForCall, struct {
		arg1 context.Context
		arg2 int64
	}{arg1, arg2})
	stub := fake.FindByIDStub
	fakeReturns := fake.findByIDReturns
	fake.recordInvocation("FindByID", []interface{}{arg1, arg2})
	fake.findByIDMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeFlowsRepository) FindByIDCallCount() int {
	fake.findByIDMutex.RLock()
	defer fake.findByIDMutex.RUnlock()
	return len(fake.findByIDArgsForCall)
}

func (fake *FakeFlowsRepository) FindByIDCalls(stub func(context.Context, int64) (model.Flow, error)) {
	fake.findByIDMutex.Lock()
	defer fake.findByIDMutex.Unlock()
	fake.FindByIDStub = stub
}

func (fake *FakeFlowsRepository) FindByIDArgsForCall(i int) (context.Context, int64) {
	fake.findByIDMutex.RLock()
	defer fake.findByIDMutex.RUnlock()
	argsForCall := fake.findByIDArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeFlowsRepository) FindByIDReturns(result1 model.Flow, result2 error) {
	fake.findByIDMutex.Lock()
	defer fake.findByIDMutex.Unlock()
	fake.FindByIDStub = nil
	fake.findByIDReturns = struct {
		result1 model.Flow
		result2 error
	}{result1, result2}
}

func (fake *FakeFlowsRepository) FindByIDReturnsOnCall(i int, result1 model.Flow, result2 error) {
	fake.findByIDMutex.Lock()
	defer fake.findByIDMutex.Unlock()
	fake.FindByIDStub = nil
	if fake.findByIDReturnsOnCall == nil {
		fake.findByIDReturnsOnCall = make(map[int]struct {
			result1 model.Flow
			result2 error
		})
	}
	fake.findByIDReturnsOnCall[i] = struct {
		result1 model.Flow
		result2 error
	}{result1, result2}
}

func (fake *FakeFlowsRepository) Pagination(arg1 context.Context, arg2 int64, arg3 int, arg4 int) ([]model.Flow, int64, error) {
	fake.paginationMutex.Lock()
	ret, specificReturn := fake.paginationReturnsOnCall[len(fake.paginationArgsForCall)]
	fake.paginationArgsForCall = append(fake.paginationArgsForCall, struct {
		arg1 context.Context
		arg2 int64
		arg3 int
		arg4 int
	}{arg1, arg2, arg3, arg4})
	stub := fake.PaginationStub
	fakeReturns := fake.paginationReturns
	fake.recordInvocation("Pagination", []interface{}{arg1, arg2, arg3, arg4})
	fake.paginationMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeFlowsRepository) PaginationCallCount() int {
	fake.paginationMutex.RLock()
	defer fake.paginationMutex.RUnlock()
	return len(fake.paginationArgsForCall)
}

func (fake *FakeFlowsRepository) PaginationCalls(stub func(context.Context, int64, int, int) ([]model.Flow, int64, error)) {
	fake.paginationMutex.Lock()
	defer fake.paginationMutex.Unlock()
	fake.PaginationStub = stub
}

func (fake *FakeFlowsRepository) PaginationArgsForCall(i int) (context.Context, int64, int, int) {
	fake.paginationMutex.RLock()
	defer fake.paginationMutex.RUnlock()
	argsForCall := fake.paginationArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeFlowsRepository) PaginationReturns(result1 []model.Flow, result2 int64, result3 error) {
	fake.paginationMutex.Lock()
	defer fake.paginationMutex.Unlock()
	fake.PaginationStub = nil
	fake.paginationReturns = struct {
		result1 []model.Flow
		result2 int64
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeFlowsRepository) PaginationReturnsOnCall(i int, result1 []model.Flow, result2 int64, result3 error) {
	fake.paginationMutex.Lock()
	defer fake.paginationMutex.Unlock()
	fake.PaginationStub = nil
	if fake.paginationReturnsOnCall == nil {
		fake.paginationReturnsOnCall = make(map[int]struct {
			result1 []model.Flow
			result2 int64
			result3 error
		})
	}
	fake.paginationReturnsOnCall[i] = struct {
		result1 []model.Flow
		result2 int64
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeFlowsRepository) UpdateOne(arg1 context.Context, arg2 model.PatchFlowParams) error {
	fake.updateOneMutex.Lock()
	ret, specificReturn := fake.updateOneReturnsOnCall[len(fake.updateOneArgsForCall)]
	fake.updateOneArgsForCall = append(fake.updateOneArgsForCall, struct {
		arg1 context.Context
		arg2 model.PatchFlowParams
	}{arg1, arg2})
	stub := fake.UpdateOneStub
	fakeReturns := fake.updateOneReturns
	fake.recordInvocation("UpdateOne", []interface{}{arg1, arg2})
	fake.updateOneMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeFlowsRepository) UpdateOneCallCount() int {
	fake.updateOneMutex.RLock()
	defer fake.updateOneMutex.RUnlock()
	return len(fake.updateOneArgsForCall)
}

func (fake *FakeFlowsRepository) UpdateOneCalls(stub func(context.Context, model.PatchFlowParams) error) {
	fake.updateOneMutex.Lock()
	defer fake.updateOneMutex.Unlock()
	fake.UpdateOneStub = stub
}

func (fake *FakeFlowsRepository) UpdateOneArgsForCall(i int) (context.Context, model.PatchFlowParams) {
	fake.updateOneMutex.RLock()
	defer fake.updateOneMutex.RUnlock()
	argsForCall := fake.updateOneArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeFlowsRepository) UpdateOneReturns(result1 error) {
	fake.updateOneMutex.Lock()
	defer fake.updateOneMutex.Unlock()
	fake.UpdateOneStub = nil
	fake.updateOneReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeFlowsRepository) UpdateOneReturnsOnCall(i int, result1 error) {
	fake.updateOneMutex.Lock()
	defer fake.updateOneMutex.Unlock()
	fake.UpdateOneStub = nil
	if fake.updateOneReturnsOnCall == nil {
		fake.updateOneReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.updateOneReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeFlowsRepository) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createOneMutex.RLock()
	defer fake.createOneMutex.RUnlock()
	fake.deleteOneMutex.RLock()
	defer fake.deleteOneMutex.RUnlock()
	fake.findByIDMutex.RLock()
	defer fake.findByIDMutex.RUnlock()
	fake.paginationMutex.RLock()
	defer fake.paginationMutex.RUnlock()
	fake.updateOneMutex.RLock()
	defer fake.updateOneMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeFlowsRepository) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ repository.FlowsRepository = new(FakeFlowsRepository)
