oauth:
  google:
    client_id: "your-client-id"
    client_secret: "your-client-secret"
    redirect_url: "http://localhost:8080/api/v1/auth/google/callback"
    scopes:
      - "https://www.googleapis.com/auth/userinfo.email"
      - "https://www.googleapis.com/auth/userinfo.profile"
  kakao:
    client_id: "your-kakao-client-id"
    client_secret: "your-kakao-client-secret"
    redirect_url: "http://localhost:8080/api/v1/auth/kakao/callback"
    scopes:
      - "account_email"
      - "profile_nickname"
